# Curso de Python Científico
## Ejercicios del módulo de NumPy

---

**Autor:** César Husillos Rodríguez

**Email:** c.husillos@igme.es

---

### Ejercicio1

Genere un array de dimensión 3x3, que tenga
* en la primera fila: 4, 5, 6
* en la segunda fila: 7, 8, 9
* en la tercera fila: 10, 11, 12

Imprima por pantalla el tamaño del array en bytes.

In [8]:
import numpy as np
datos = np.array(np.arange(4,13))
print(datos)
print(datos.shape)
print(datos.reshape(3,3)) 
datos = np.array(([4,5,6], [7,8,9], [10,11,12]))
print(datos)
print(datos.shape)
print(datos.nbytes)

[ 4  5  6  7  8  9 10 11 12]
(9,)
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(3, 3)
36


### Ejercicio 2

Cree un array con 10 elementos en el intervalo [-2,2] y equidistantes entre ellos.

In [10]:
datos = (np.linspace(-2,2, 10, endpoint=True))
print(datos)


[-2.         -1.55555556 -1.11111111 -0.66666667 -0.22222222  0.22222222
  0.66666667  1.11111111  1.55555556  2.        ]


### Ejercicio 3

Cree un array cuyos elementos sean los enteros pares en [1,100] y en orden decreciente.

In [13]:
datos=(np.array(np.arange(100,1,-2)))
print(datos)

[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]


### Ejercicio 4

Genere un array bidimensional de números enteros aletatorios que tenga 4 filas y 5 columnas. Los aleatorios generados estarán en el intervalo cerrado [0, 10].

In [47]:
datos4 = np.random.randint(0, 11, size=(4, 5))
print(datos4)
# help(np.random.randint)

[[ 1  6  4  6 10]
 [10  0  3  4  7]
 [ 1  1  8  2  3]
 [ 5  0  9  7  9]]


### Ejercicio 5

Genere un array de booleanos a partir del array del ejercicio 4. 

**Nota:** Se trata de hacer un cambio de tipo de dato almacenado por el array.

In [48]:
datos4
print(datos4)
# help(np.empty_like)
datos5 = np.empty_like(datos4, dtype= bool )
print(datos5)

datos55 = np.ones_like(datos4, dtype= bool )
print(datos55)

datos555 = np.full_like(datos4,0, dtype= bool )
print(datos555)


[[ 1  6  4  6 10]
 [10  0  3  4  7]
 [ 1  1  8  2  3]
 [ 5  0  9  7  9]]
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


### Ejercicio 6

Genere un array a usando las palabras contenidas en la siguiente frase: "En un lugar de La Mancha, de cuyo nombre no quiero acordarme". Imprima el tipo del array por pantalla y las dimensiones de ese array.

**Pista:** Asigne la cadena de caracteres a una variable llamada, por ejemplo, "texto". Después debe "romper" la cadena por los espacios en blanco " " y usar las palabras para crear un array. Esto se puede hacer con el método *split* de Python. Si no se acuerda, use la función help(texto.split) para obtener información.

In [ ]:
texto = "En un lugar de La Mancha, de cuyo nombre no quiero acordarme"
#help(texto.split)

### Ejercicio 7

Genere un array de números decimales y de dimensiones 3x1. Todos los elementos del array deben ser igual a 5.0. Imprima su forma (*shape*)

Modifique la forma del array de forma que el resultado sea un array unidimensional. Imprima la nueva forma del array.

### Ejercicio 8

Genere un array aleatorio de números enteros entre -5 y 5, que tenga 3 filas y 2 columnas. Imprima el array por pantalla.

Modifique el array de forma que los valores que están en las filas pasen estar en las columnas y viceversa.

**Pista:** Básicamente se le pide que transponga ese array.

### Ejercicio 9

Genere un array números enteros crecientes. Contendrá los valores del 0 al 10. Se le pide que:
* muestre el segundo elemento. 
* muestre los dos últimos.
* muestre los elementos que ocupan las posiciones 0, 2, 4, 6, 8 y 10.

In [52]:
datos = np.arange(0,11)
print(datos)
print(datos[1])
print(datos[-2:])
print(datos[::2])

[ 0  1  2  3  4  5  6  7  8  9 10]
1
[ 9 10]
[ 0  2  4  6  8 10]


### Ejercicio 10

Dado el array que se le muestra en la siguiente celda, seleccione los elementos de las esquinas.

In [57]:
import numpy as np
datos = np.array([[2, 4, 6, 8],[1, 3, -2, 5], [7, 3, 4, 4], [3, 6, 3, 9]])
print(datos)

# Siga escribiendo la solución al ejercicio en la línea siguiente
datos[[0,0,-1,-1], [0,-1,0,-1]] #forma genérica de sacar las esquinas de una matriz


[[ 2  4  6  8]
 [ 1  3 -2  5]
 [ 7  3  4  4]
 [ 3  6  3  9]]


array([2, 8, 3, 9])

### Ejercicio 11

Dado el array del ejercicio anterior, seleccione los índices adecuados para obtener la submatriz

4 6
3 -2
3 4

In [66]:
datos = np.array([[2, 4, 6, 8],[1, 3, -2, 5], [7, 3, 4, 4], [3, 6, 3, 9]])
print(datos)
print()

datos[:-1 , 1:3]

[[ 2  4  6  8]
 [ 1  3 -2  5]
 [ 7  3  4  4]
 [ 3  6  3  9]]



array([[ 4,  6],
       [ 3, -2],
       [ 3,  4]])

### Ejercicio 12

Dado el array que se define en la siguiente celda, seleccione e imprima la primera y la tercera fila.

In [ ]:
datos = np.arange(20).reshape((10, 2))
print(datos)

# Escriba la solución del ejercicio en la siguiente línea de esta celda


### Ejercicio 13

Dado el tensor (array 3D) definido en la celda siguiente, devuelva la segunda capa mediante indexación.

**Pista:** Lo que pide el ejercicio es que usando la indexación adecuada, devuelva la submatriz 

\begin{matrix}
8 & 1 & 7 & 4\\
4 & 2 & 8 & 4
\end{matrix}


In [ ]:
datos = np.random.randint(low=0, high=10, size=(3, 2, 4))
print(datos)

# Resuelva el ejercicio en las siguientes líneas de esta celda

### Ejercicio 14

Genere un array con los enteros consecutivos de 20 al 1. Sustituya los números en el intervalo [5, 12] por el valor 0.

### Ejercicio 15

Dada la matriz definida en la celda siguiente, sustituya los elementos de la diagonal principal por 1.

### Ejercicio 16

Dado el array definido en la siguiente celda, genere otro array en el que los elementos correspondan a la suma de los valores de cada fila del original.

In [9]:
import numpy as np
datos = np.arange(20).reshape((10, 2))
print(datos)

# Escriba la solución del ejercicio en la siguiente línea de esta celda
print((datos[:,0])+ datos[:, 1])
#  o tambien
suma_filas = np.sum(datos, axis=1)
print(suma_filas)
#  o tmb
np.add(datos[:,0], datos[:,1])
print(suma_filas)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
[ 1  5  9 13 17 21 25 29 33 37]
[ 1  5  9 13 17 21 25 29 33 37]
[ 1  5  9 13 17 21 25 29 33 37]


### Ejercicio 17

Escriba el resultado de calcular la función seno para aquellos puntos separados $\pi /4$ en el intervalo [-3\pi, 5\pi].

In [12]:
# obtener valores x
intervalor = np.arange(-3*np.pi, 5.1*np.pi, np.pi/4)
print(intervalor)
# aplicar seno a los valores x
resultado = np.sin(intervalor)
print(resultado)

[-9.42477796e+00 -8.63937980e+00 -7.85398163e+00 -7.06858347e+00
 -6.28318531e+00 -5.49778714e+00 -4.71238898e+00 -3.92699082e+00
 -3.14159265e+00 -2.35619449e+00 -1.57079633e+00 -7.85398163e-01
  1.06581410e-14  7.85398163e-01  1.57079633e+00  2.35619449e+00
  3.14159265e+00  3.92699082e+00  4.71238898e+00  5.49778714e+00
  6.28318531e+00  7.06858347e+00  7.85398163e+00  8.63937980e+00
  9.42477796e+00  1.02101761e+01  1.09955743e+01  1.17809725e+01
  1.25663706e+01  1.33517688e+01  1.41371669e+01  1.49225651e+01]
[-3.67394040e-16 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
  3.79764304e-15  7.07106781e-01  1.00000000e+00  7.07106781e-01
 -7.22789204e-15 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
  1.06581410e-14  7.07106781e-01  1.00000000e+00  7.07106781e-01
 -1.40883900e-14 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
  1.75186390e-14  7.07106781e-01  1.00000000e+00  7.07106781e-01
 -2.09488880e-14 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
  2.43791370e-14  7.0710

### Ejercicio 18

Dado el conjunto de puntos definidos en el array de la celda siguiente, determine el valor de aplicar el logaritmo en base $e$ al resultado del cálculo de la exponencial de cada elemento.

**Pista:** El problema pide que realice la siguiente operación sobre cada elemento del array: $log_e(e^x)$, donde $x$ es cada uno de los elementos del array.

In [17]:
datos = np.array([2, 4, 3, 8 ,12])

# Continúe el ejercicio en las líneas siguientes.
def calcular(x):
    np.log(np.e^x)
datos2 = np.exp(datos) #exponencial
print(datos2)
datos3 = np.log(datos2) # logartomo
print(datos3)
resultado = np.log(np.exp(datos))
print(resultado)

[7.38905610e+00 5.45981500e+01 2.00855369e+01 2.98095799e+03
 1.62754791e+05]
[ 2.  4.  3.  8. 12.]
[ 2.  4.  3.  8. 12.]


### Ejercicio 19

Dados los arrays *a* y *b* definidos en la celda siguiente, determine
* Cuáles son los valores de *a* que están en *b*.
* El número de valores diferentes que hay en *a*.
* Los valores de *a* y de *b* que no están en ambos conjuntos. 

In [ ]:
a = np.array([[2, 3, 6], [5, 5, 7]])
b = np.arange(5)

# Escriba la solución del ejercicio en la siguiente línea de esta celda


### Ejercicio 20

Dado un array de enteros entre 0 y 13, determine aquellos que son impares y múltiplos de 3. Muestrelos por pantalla.

In [30]:
array = np.arange(0,14)
print(array)
posiciones_impares = (array % 2 ==1) 
multi_3 =  (array %3 == 0)
print(posiciones_impares)
print(multi_3)

resultado = np.logical_and(posiciones_impares, multi_3)
print(resultado)
print(any(resultado))
print('Ssolucion al ejericio', array[resultado])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[False  True False  True False  True False  True False  True False  True
 False  True]
[ True False False  True False False  True False False  True False False
  True False]
[False False False  True False False False False False  True False False
 False False]
True
Ssolucion al ejericio [3 9]


### Ejercicio 21

Dado el array definido en la siguiente celda, devuelva aquellos que corresponden a un año bisiesto. Genere un array con los años bisiestos ordenados de mayor a menor. Escriba también el porcentaje de años bisiestos contenidos en el array.

**Pista:** Un año se considera bisiesto si es múltiplo de 4 y de 100, pero no de 400.

In [ ]:
datos = np.array([4, 1000, 2024, 400, 800, 666, 2012, 2040])

# Escriba la solución del ejercicio en la siguiente línea de esta celda

### Ejercicio 22

Genere un array ordenado de menor a mayor de 20 números enteros aleatorios entre 0 y 13. 

In [33]:
array = np.random.randint(0, 14, size=(20))
print(array)
ordenado2 = np.sort(array)
print(ordenado2)

[ 1  4 13  4  3  9  3  6 11  4  5 13  5 10 10  0 11  4  1 10]
[ 0  1  1  3  3  4  4  4  4  5  5  6  9 10 10 10 11 11 13 13]


### Ejercicio 23

Obtenga las posiciones del array definido en la siguiente celda de forma que sus valores se ordenen de menor a mayor. Use dichas posiciones para ordenar el array de menor a mayor.

In [35]:
datos = np.array((0, 1, 15, 8, 9, 17))
print(datos)

# Escriba la solución del ejercicio en la siguiente línea de esta celda
indices_ordenados = np.argsort(datos)
array_ordenado = datos[indices_ordenados]
print('los indices son', indices_ordenados)
print('el array ordenado es ', array_ordenado)

[ 0  1 15  8  9 17]
los indices son [0 1 3 4 2 5]
el array ordenado es  [ 0  1  8  9 15 17]


### Ejercicio 24

Dado el array definido en la siguiente celda, elimine los números que sean *np.nan*. Muestre el resultado del array modificado y el número de elementos que contiene.

In [44]:
datos = np.arange(10, dtype=float)
datos[np.random.randint(0, 10, 3)] = np.nan

print(datos)

# Escriba la solución del ejercicio en la siguiente línea de esta celda
# np.isnan(datos)

condicion = datos[np.logical_not(np.isnan(datos))]
resultado = np.extract(condicion, datos) 
print(resultado)
print(resultado.size)

[nan nan  2.  3.  4.  5.  6.  7. nan  9.]
[nan nan  2.  3.  4.  5.  6.]
7


### Ejercicio 25

Genere un array de enteros aleatorios entre 1931 y 2024 y dimensiones 4 x 5. Almacene dicho array en un fichero de nombre 'numeros.csv'. Los números deben estar separados por comas.

### Ejercicio 26

Recupere en un array el contenido del fichero 'numeros.csv'. El array debe ser de números enteros y también debe tener dimensiones 4x5.

### Ejercicio 27

Concatene a las columnas del array *a*, las columnas del array *b* definidos en la siguiente celda. Muestre el resultado por pantalla.

In [47]:
a = np.arange(6).reshape((2,3))
b = np.zeros((2, 2), dtype=float)
print('a')
print(a)
print('b')
print(b)

# Escriba la solución del ejercicio en la siguiente línea de esta celda
np.hstack((a,b))

a
[[0 1 2]
 [3 4 5]]
b
[[0. 0.]
 [0. 0.]]


array([[0., 1., 2., 0., 0.],
       [3., 4., 5., 0., 0.]])

### Ejercicio 28

Agregue al array *b* del ejercicio anterior una columna más a la izquierda con valores iguales a 1. Concatene las filas del array *a* del ejercicio anterior con el array *b* que acaba de modificar. Muestre el resultado por pantalla. 

### Ejercicio 29

Dado el array de precipitaciones de los ultimos 10 días disponible en la siguiente celda, calcule:
* el acumulado de precipitación diaria.
* La posición del día con menor precipitación.
* El valor de la precipitación máxima.
* el valor mediano, la media y la desviación estándar del conjunto de valores.

In [60]:
datos = np.array([12.5, 6.1, 0.0, 23.8, 10.4, 5.9, 3.3, 0.0, 0.0])
print(datos)

# Escriba la solución del ejercicio en la siguiente línea de esta celda
print(np.sum(datos))

np.arange(datos.size)[np.amin(datos)==datos] # posicion de dias de minima precipitacion
datos.argmin() # devuelve posiciones en elarray enque se alcanzan valores minimos (maximo argmax)
#  valor de la precipitacion maxima
print(np.amax(datos))
print(np.average(datos))
print(np.mean(datos))
print(np.median(datos))
print(max(datos))
print(datos.max())

[12.5  6.1  0.  23.8 10.4  5.9  3.3  0.   0. ]
62.00000000000001
23.8
6.888888888888889
6.888888888888889
5.9
23.8
23.8


### Ejercicio 30

Simule el lanzamiento de un dado 100 veces. Responda a esta pregunta: ¿su dado está cargado?

**Pista:** En un dado equilibrado, existe la misma probabilidad de obtener un número que cualquier otro. Idealmente, las veces que obtenemos un número debería ser igual a $1/6$. A efectos prácticos, consideraremos que un dado está cargado si la probabilidad de obtener un número difiere en un 10% de la probabilidad ideal.

### Ejercicio 31

Obtenga una distibución de 10 datos según una distribución normal de media 10 y desviación estándar 2. A continuación calcule la media y la desviación estándar de los 10 datos. ¿Se aproximan a los valores con los que fueron generados?

Pruebe a hacer lo mismo pero generando 100, 1.000 y 10.000 datos aleatorios. ¿Se aproxima la media y la desviación estándar más ahora? Escriba el valor absoluto de la diferencia entre los valores promedio de su muestra y 10.

**Nota:** Lo que tratamos de demostrar es que se cumple el *Teorema del límite central* (https://es.wikipedia.org/wiki/Teorema_del_l%C3%ADmite_central)