# Curso de Python Científico
## Ejercicios del módulo de NumPy

---

**Autor:** César Husillos Rodríguez

**Email:** c.husillos@igme.es

---

### Ejercicio1

Genere un array de dimensión 3x3, que tenga
* en la primera fila: 4, 5, 6
* en la segunda fila: 7, 8, 9
* en la tercera fila: 10, 11, 12

Imprima por pantalla el tamaño del array en bytes.

In [1]:
import numpy as np

datos = np.array([[4,5,6], [7,8,9], [10,11,12]])
print(datos)

print(datos.nbytes)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
36


### Ejercicio 2

Cree un array con 10 elementos en el intervalo [-2,2] y equidistantes entre ellos.

In [7]:
datos = np.linspace(-2, 2, 10, endpoint=True)
print(datos)

[-2.         -1.55555556 -1.11111111 -0.66666667 -0.22222222  0.22222222
  0.66666667  1.11111111  1.55555556  2.        ]


### Ejercicio 3

Cree un array cuyos elementos sean los enteros pares en [1,100] y en orden decreciente.

In [8]:
datos = np.arange(100, 0, -2)
print(datos)

[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]


In [9]:
# help(np.arange)

### Ejercicio 4

Genere un array bidimensional de números enteros aletatorios que tenga 4 filas y 5 columnas. Los aleatorios generados estarán en el intervalo cerrado [0, 10].

In [10]:
datos4 = np.random.randint(0, 11, (4,5))
print(datos4)

[[5 2 6 0 2]
 [8 6 3 8 8]
 [5 9 2 8 9]
 [7 1 6 4 3]]


In [11]:
# help(np.random.randint)

### Ejercicio 5

Genere un array de booleanos a partir del array del ejercicio 4. 

**Nota:** Se trata de hacer un cambio de tipo de dato almacenado por el array.

In [12]:
datos5 = np.full_like(datos4, -2, dtype=bool)
print(datos5)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [13]:
#help(np.full_like)

### Ejercicio 6

Genere un array a usando las palabras contenidas en la siguiente frase: "En un lugar de La Mancha, de cuyo nombre no quiero acordarme". Imprima el tipo del array por pantalla y las dimensiones de ese array.

**Pista:** Asigne la cadena de caracteres a una variable llamada, por ejemplo, "texto". Después debe "romper" la cadena por los espacios en blanco " " y usar las palabras para crear un array. Esto se puede hacer con el método *split* de Python. Si no se acuerda, use la función help(texto.split) para obtener información.

In [14]:
texto = "En un lugar de La Mancha, de cuyo nombre no quiero acordarme"

In [15]:
#help(texto.split)

In [16]:
palabras = texto.split()
print(palabras)

['En', 'un', 'lugar', 'de', 'La', 'Mancha,', 'de', 'cuyo', 'nombre', 'no', 'quiero', 'acordarme']


In [18]:
datos6 = np.array(palabras)
print('array de palabras = ', datos6)
print('Tamaño del array de palabras =', datos6.size)
print('Forma del array de palabras =', datos6.shape)
print('Tipo del array de palabras =', datos6.dtype)

array de palabras =  ['En' 'un' 'lugar' 'de' 'La' 'Mancha,' 'de' 'cuyo' 'nombre' 'no' 'quiero'
 'acordarme']
Tamaño del array de palabras = 12
Forma del array de palabras = (12,)
Tipo del array de palabras = <U9


### Ejercicio 7

Genere un array de números decimales y de dimensiones 3x1. Todos los elementos del array deben ser igual a 5.0. Imprima su forma (*shape*)

Modifique la forma del array de forma que el resultado sea un array unidimensional. Imprima la nueva forma del array.

In [21]:
datos7 = np.full((3, 1), 5.0)
print(datos7)
print('Forma del array datos7 =', datos7.shape)

# Cambio la forma de datos7 para que sea un array 1D
datos7 = datos7.flatten()
print('Forma del array modificado =', datos7.shape)

[[5.]
 [5.]
 [5.]]
Forma del array datos7 = (3, 1)
Forma del array modificado = (3,)


### Ejercicio 8

Genere un array aleatorio de números enteros entre -5 y 5, que tenga 3 filas y 2 columnas. Imprima el array por pantalla.

Modifique el array de forma que los valores que están en las filas pasen estar en las columnas y viceversa.

**Pista:** Básicamente se le pide que trasponga ese array.

In [23]:
# help(np.random.randint)

In [24]:
datos8 = np.random.randint(-5, 6, size=(3, 2))
print('Array de número enteros aleatorios =')
print(datos8)

# modifico el array para que las filas pasen a columnas y vicecersa. Es lo mismo que "trasponer" un array
datos8 = np.transpose(datos8)
print('Array modificado =')
print(datos8)

Array de número enteros aleatorios =
[[-1 -4]
 [ 3 -3]
 [ 0 -3]]
Array modificado =
[[-1  3  0]
 [-4 -3 -3]]


### Ejercicio 9

Genere un array números enteros crecientes. Contendrá los valores del 0 al 10. Se le pide que:
* muestre el segundo elemento. 
* muestre los dos últimos.
* muestre los elementos que ocupan las posiciones 0, 2, 4, 6, 8 y 10.

In [52]:
datos = np.arange(0,11)
print(datos)

print('Segundo elemento = ', datos[1])
print('Dos últimos elementos = ', datos[-2:]) 
print('Posiciones [0, 2, 4, 6, 8 y 10] = ', datos[::2])

[ 0  1  2  3  4  5  6  7  8  9 10]
Segundo elemento =  1
Dos últimos elementos =  [ 9 10]
Posiciones [0, 2, 4, 6, 8 y 10] =  [ 0  2  4  6  8 10]


### Ejercicio 10

Dado el array que se le muestra en la siguiente celda, seleccione los elementos de las esquinas.

In [55]:
import numpy as np
datos = np.array([[2, 4, 6, 8],[1, 3, -2, 5], [7, 3, 4, 4], [3, 6, 3, 9]])
print(datos)


# Siga escribiendo la solución al ejercicio en la línea siguiente
seleccion_esquinas = datos[[0,0,-1,-1], [0,-1,0,-1]]
print(seleccion_esquinas)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  4 15 19]


### Ejercicio 11

Dado el array definido en la siguiente celda, seleccione los índices adecuados para obtener la submatriz

\begin{matrix}
4 & 6\\
3 & -2\\
3 & 4
\end{matrix}

In [25]:
datos = np.array([[2, 4, 6, 8],[1, 3, -2, 5], [7, 3, 4, 4], [3, 6, 3, 9]])
print(datos)

# Escriba la solución al ejercicio en la siguiente línea de esta celda
solucion = datos[:-1,1:3]
print('solucion =')
print(solucion)

[[ 2  4  6  8]
 [ 1  3 -2  5]
 [ 7  3  4  4]
 [ 3  6  3  9]]
solucion =
[[ 4  6]
 [ 3 -2]
 [ 3  4]]


### Ejercicio 12

Dado el array que se define en la siguiente celda, seleccione e imprima la primera y la tercera fila.

In [28]:
datos = np.arange(20).reshape((10, 2))
print(datos)

# Escriba la solución del ejercicio en la siguiente línea de esta celda
datos12 = datos[[0,2],:]
print('Primera y tercera filas: ')
print(datos12)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
Primera y tercera filas: 
[[0 1]
 [4 5]]


### Ejercicio 13

Dado el tensor (array 3D) definido en la celda siguiente, devuelva la segunda capa mediante indexación.

In [31]:
datos = np.random.randint(low=0, high=10, size=(3, 2, 4))
print(datos)

# Resuelva el ejercicio en las siguientes líneas de esta celda
segunda_capa = datos[1,:,:]
print('Segunda capa:')
print(segunda_capa)

[[[6 7 4 4]
  [8 4 4 4]]

 [[4 4 6 7]
  [5 9 1 4]]

 [[5 1 5 3]
  [4 9 8 5]]]
Segunda capa:
[[4 4 6 7]
 [5 9 1 4]]


### Ejercicio 14

Genere un array con los enteros consecutivos de 20 al 1. Sustituya los números en el intervalo [5, 12] por el valor 0.

In [37]:
# genero el array de enteros consecutivos del 1 al 20
datos14 = np.arange(1, 21)
print(datos14)

# uso un rango que tome los valores del 5 al 12
datos14[4:12] = 0
# invierto el orden del array
datos14 = datos14[::-1]
print('Array modificado:')
print(datos14)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Array modificado:
[20 19 18 17 16 15 14 13  0  0  0  0  0  0  0  0  4  3  2  1]


### Ejercicio 15

Dada la matriz definida en la celda siguiente, sustituya los elementos de la diagonal principal por 1.

In [43]:
datos15 = np.full((5, 5), 2, dtype=int)
print('Array original:')
print(datos15)

# Resuelva el ejercicio en las siguientes líneas de esta celda

# Si lo hacemos seleccionando índices de forma manual, necesitamos 
# cinco índices para filas y cinco para columnas.
ind_fil = np.arange(5, dtype=int) # secuencia de enteros de 0 hasta 4
print('Indices de filas =', ind_fil)

# Ambos índices de la diagonal principal son iguales
ind_col = ind_fil

# Ahora hago el cambio de valor de la diagonal principal
datos15[ind_fil, ind_col] = 1
print('Array modificado: ')
print(datos15)

# La forma elegante y profesional (hay que conocer mucho sobre NumPy porque siempre se escapa algo)
# ind = np.diag_indices_from(datos15)
# datos15[ind] = 1

Array original:
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
Indices de filas = [0 1 2 3 4]
Array modificado: 
[[1 2 2 2 2]
 [2 1 2 2 2]
 [2 2 1 2 2]
 [2 2 2 1 2]
 [2 2 2 2 1]]


### Ejercicio 16

Dado el array definido en la siguiente celda, genere otro array en el que los elementos correspondan a la suma de los valores de cada fila del original.

In [2]:
datos = np.arange(20).reshape((10, 2))
print(datos)

# Escriba la solución del ejercicio en la siguiente línea de esta celda


[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [3]:
# Solución de Rubén
suma = datos[:,0] + datos[:,1]
print(suma)

[ 1  5  9 13 17 21 25 29 33 37]


In [4]:
# Luis Miguel
suma_filas = np.sum(datos, axis=1)
print(suma_filas)

[ 1  5  9 13 17 21 25 29 33 37]


In [5]:
# Ana
print(np.add(datos[:,0], datos[:,1]))

[ 1  5  9 13 17 21 25 29 33 37]


### Ejercicio 17

Escriba el resultado de calcular la función $\sin(x)$ para aquellos puntos separados $\pi /4$ en el intervalo $[-3\pi, 5\pi]$.

In [13]:
x = np.arange(-3 * np.pi, 5 * np.pi + np.pi / 4, np.pi / 4)
resultado = np.sin(x)
print(resultado)

[-3.67394040e-16 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
  3.79764304e-15  7.07106781e-01  1.00000000e+00  7.07106781e-01
 -7.22789204e-15 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
  1.06581410e-14  7.07106781e-01  1.00000000e+00  7.07106781e-01
 -1.40883900e-14 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
  1.75186390e-14  7.07106781e-01  1.00000000e+00  7.07106781e-01
 -2.09488880e-14 -7.07106781e-01 -1.00000000e+00 -7.07106781e-01
  2.43791370e-14  7.07106781e-01  1.00000000e+00  7.07106781e-01
 -2.78093860e-14]


In [12]:
# help(np.linspace)

### Ejercicio 18

Dado el conjunto de puntos definidos en el array de la celda siguiente, determine el valor de aplicar el logaritmo en base $e$ al resultado del cálculo de la exponencial de cada elemento.

**Pista:** El problema pide que realice la siguiente operación sobre cada elemento del array: $log_e(e^x)$, donde $x$ es cada uno de los elementos del array.

In [16]:
datos = np.array([2, 4, 3, 8 ,12])

# Continúe el ejercicio en las líneas siguientes.

exponencial = np.exp(datos)
print(exponencial)
resultado = np.log(exponencial)
print('resultado = ', resultado)

[7.38905610e+00 5.45981500e+01 2.00855369e+01 2.98095799e+03
 1.62754791e+05]
resultado =  [ 2.  4.  3.  8. 12.]


In [20]:
print(np.log(np.exp(datos)))

[ 2.  4.  3.  8. 12.]


### Ejercicio 19

Dados los arrays *a* y *b* definidos en la celda siguiente, determine
* Cuáles son los valores de *a* que están en *b*.
* El número de valores diferentes que hay en *a*.
* Los valores de *a* y de *b* que no están en ambos conjuntos. 

In [6]:
a = np.array([[2, 3, 6], [5, 5, 7]])
b = np.arange(5)

# Escriba la solución del ejercicio en la siguiente línea de esta celda

# Elementos de a que están en b
bool_estan = np.in1d(a,b) # array de booleanos 1D
print('Elementos de a en b =', np.ravel(a)[np.in1d(a, b)])

# Número de valores diferentes que hay en a
diferentes = np.unique(a)
print('Elementos únicos en a =', diferentes)
print('Número de elementos diferentes en a =', diferentes.size)

# valores de a y de b que no están en ambos conjuntos.
# hago la unión de ambos
union = np.union1d(a, b)
# determino la interseccion
inters = np.intersect1d(a, b)
# el resultado es los elementos de la unión quitando los de la intersección
print('Resultado =', np.setdiff1d(union, inters))

Elementos de a en b = [2 3]
Elementos únicos en a = [2 3 5 6 7]
Número de elementos diferentes en a = 5
Resultado = [0 1 4 5 6 7]


### Ejercicio 20

Dado un array de enteros entre 0 y 13, determine aquellos que son impares y múltiplos de 3. Muestrelos por pantalla.

In [23]:
datos = np.arange(0, 14)

impares = (datos % 2 == 1)
multiplos_3 = (datos % 3 == 0)

resultado = np.logical_and(impares, multiplos_3)
print(resultado)
print('Solución al ejercicio: ', datos[resultado])

[False False False  True False False False False False  True False False
 False False]
Solución al ejercicio:  [3 9]


### Ejercicio 21

Dado el array definido en la siguiente celda, devuelva aquellos que corresponden a un año bisiesto. Genere un array con los años bisiestos ordenados de mayor a menor. Escriba también el porcentaje de años bisiestos contenidos en el array.

**Pista:** Un año se considera bisiesto si es múltiplo de 4 y no de 100, pero sí de 400.

In [9]:
datos = np.array([4, 1000, 2024, 400, 800, 666, 2012, 2040])

# Escriba la solución del ejercicio en la siguiente línea de esta celda
# condiciones
condicion1 = datos % 4 == 0
condicion2 = datos % 100 == 0
condicion3 = datos % 400 != 0

#compongo la lógica de bisiestos
cond_intermedia = np.logical_or(condicion2, condicion3)
cond_bisiesto = np.logical_and(cond_intermedia, condicion1)

# aplico la condicion de bisiesto al array de datos
bisiestos = np.extract(cond_bisiesto, datos)
# ordeno los años
bisiestos = np.sort(bisiestos)
# imprimo el array ordenado
print(bisiestos)

[   4  400  800 1000 2012 2024 2040]


### Ejercicio 22

Genere un array ordenado de menor a mayor de 20 números enteros aleatorios entre 0 y 13. 

In [25]:
#Károly
# 1. generación de 20 enteros aleatorios entre 0 y 13
mi_array = np.random.randint(0, 14, size = 20)
# 2. ordenación del array de aleatorios
mi_array2 = np.sort(mi_array)
print(mi_array)
print(mi_array2)

[ 9  8  3  9  7  0 11  7  2  3  8  6  2  6  0  5 11 11  7  4]
[ 0  0  2  2  3  3  4  5  6  6  7  7  7  8  8  9  9 11 11 11]


In [26]:
# JM Gomez
aleatorios = np.random.randint(0, 14, size=20)
print(aleatorios)
ordenados = np.sort(aleatorios)
print(ordenados)

[ 4  4 12 10 12 10  9 13 13  0  9  8  9  3  4  7  8  6  1  9]
[ 0  1  3  4  4  4  6  7  8  8  9  9  9  9 10 10 12 12 13 13]


### Ejercicio 23

Obtenga las posiciones del array definido en la siguiente celda de forma que sus valores se ordenen de menor a mayor. Use dichas posiciones para ordenar el array de menor a mayor.

In [11]:
datos = np.array((0, 1, 15, 8, 9, 17))
print(datos)

# Escriba la solución del ejercicio en la siguiente línea de esta celda
indices_ordenados = np.argsort(datos)
print('array ordenado =', datos[indices_ordenados])

[ 0  1 15  8  9 17]
array ordenado = [ 0  1  8  9 15 17]


### Ejercicio 24

Dado el array definido en la siguiente celda, elimine los números que sean *np.nan*. Muestre el resultado del array modificado y el número de elementos que contiene.

In [28]:
datos = np.arange(10, dtype=float)
datos[np.random.randint(0, 10, 3)] = np.nan

print(datos)

# Escriba la solución del ejercicio en la siguiente línea de esta celda
condicion = np.logical_not(np.isnan(datos)) # los elementos NO nan
resultado = np.extract(condicion, datos)
print(resultado)
print('Numero de valores NO nan =', resultado.size)

[ 0.  1. nan  3. nan  5.  6. nan  8.  9.]
[0. 1. 3. 5. 6. 8. 9.]
Numero de valores NO nan = 7


### Ejercicio 25

Genere un array de enteros aleatorios entre 1931 y 2024 y dimensiones 4 x 5. Almacene dicho array en un fichero de nombre 'numeros.csv'. Si abre el fichero con cualquier editor de texto, los números deben estar separados por comas.

In [19]:
# genero enteros aleatorios
datos =np.random.randint(1931, 2025, (4, 5))
#guardo en fichero
np.savetxt('numeros.csv', datos, fmt='%d', delimiter=',')
# muestro el contenido
with open('numeros.csv') as fichero:
    print(fichero.read())

1992,1958,1956,2019,1970
1988,1975,1992,1954,1938
1966,1999,1987,1987,1972
1982,1978,1996,1994,1973



### Ejercicio 26

Recupere en un array el contenido del fichero 'numeros.csv'. El array debe ser de números enteros y también debe tener dimensiones 4x5.

In [22]:
recuperados = np.loadtxt('numeros.csv', dtype=int, delimiter=',')
print(recuperados)
print('tipo de dato del array =', recuperados.dtype)

[[1992 1958 1956 2019 1970]
 [1988 1975 1992 1954 1938]
 [1966 1999 1987 1987 1972]
 [1982 1978 1996 1994 1973]]
tipo de dato del array = int32


### Ejercicio 27

Concatene las columnas del array *a*, y las del array *b* definidos en la siguiente celda. Muestre el resultado por pantalla.

In [37]:
a = np.arange(6).reshape((2,3))
b = np.zeros((2, 2), dtype=float)
print('a')
print(a)
print('b')
print(b)

# Escriba la solución del ejercicio en la siguiente línea de esta celda
super_array = np.hstack((a,b))
print(super_array)

a
[[0 1 2]
 [3 4 5]]
b
[[0. 0.]
 [0. 0.]]
[[0. 1. 2. 0. 0.]
 [3. 4. 5. 0. 0.]]


### Ejercicio 28

Agregue al array *b* del ejercicio anterior una columna más a la izquierda con valores iguales a 1. Concatene las filas del array *a* del ejercicio anterior con el array *b* que acaba de modificar. Muestre el resultado por pantalla. 

In [40]:
# nueva columna
nuevo = np.ones((2, 1), dtype=int)
# agrego al array b por la izquierda
nuevo_b = np.hstack((nuevo, b))
# ahora concateno las filas de a y nuevo_b y lo muestro por pantalla
print(np.vstack((a, nuevo_b)))

[[0. 1. 2.]
 [3. 4. 5.]
 [1. 0. 0.]
 [1. 0. 0.]]


### Ejercicio 29

Dado el array de precipitaciones de los ultimos 10 días disponible en la siguiente celda, calcule:
* el acumulado de precipitación diaria.
* La posición del día con menor precipitación.
* El valor de la precipitación máxima.
* el valor mediano, la media y la desviación estándar del conjunto de valores.

In [45]:
datos = np.array([12.5, 6.1, 0.0, 23.8, 10.4, 5.9, 3.3, 0.0, 0.0])
print(datos)

# Escriba la solución del ejercicio en la siguiente línea de esta celda
print(np.sum(datos)) # Ana
print('Posicion de dias de minima precipitacion', np.arange(datos.size)[np.amin(datos) == datos])
print('Primer día de mínima precipitacion =', datos.argmin()) # Ana
print('Precipitación máxima =', np.amax(datos))
print('Precipitación máxima =', datos.max())
print('Mediana, media, desviación =', np.median(datos), np.mean(datos), np.std(datos))

[12.5  6.1  0.  23.8 10.4  5.9  3.3  0.   0. ]
62.00000000000001
Posicion de dias de minima precipitacion [2 7 8]
Primer día de mínima precipitacion = 2
Precipitación máxima = 23.8
Precipitación máxima = 23.8
Mediana, media, desviación = 5.9 6.888888888888889 7.353373291587482


In [46]:
lista = [1, 4, 5]
max(lista)
np.

5

In [34]:
help(np.amin)

Help on _ArrayFunctionDispatcher in module numpy:

amin(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Return the minimum of an array or minimum along an axis.
    
    `amin` is an alias of `~numpy.min`.
    
    See Also
    --------
    min : alias of this function
    ndarray.min : equivalent method



### Ejercicio 30

Simule el lanzamiento de un dado 100 veces. Responda a esta pregunta: ¿su dado está cargado?

**Pista:** En un dado equilibrado, existe la misma probabilidad de obtener un número que cualquier otro. Idealmente, las veces que obtenemos un número debería ser igual a $1/6$. A efectos prácticos, consideraremos que un dado está cargado si la probabilidad de obtener un número difiere en un 10% de la probabilidad ideal.

In [29]:
# Gererador de enteros
rng = np.random.default_rng(seed=5342452)

# numero de tiradas
tiradas = 100

probabilidad_dado = 1 / 6

# calculo el límite de apariciones de cada tirada. Si se supera, el dado está cargado
limite_cargado = 1.1 *(probabilidad_dado * tiradas) # el '1.1' tiene que ver con el 10% mencionado en el enunciado
print('limite de apariciones de una tirada =', limite_cargado)

# vamos a suponer que no está cargado. Si lo está, lo cambiaremos
cargado = False

# lanzamientos
lanzamientos = rng.integers(1, 7, tiradas)
for puntos in np.unique(lanzamientos):
    res = lanzamientos[lanzamientos==puntos].size
    print('Número de ocurrencias de ', puntos, '=', res)
    if res >= limite_cargado:
        cargado = True

# Imprimo el resultado
if cargado == True:
    print('El dado está cargado')
else:
    print('El dado no está cargado')
    

limite de apariciones de una tirada = 18.333333333333332
Número de ocurrencias de  1 = 15
Número de ocurrencias de  2 = 13
Número de ocurrencias de  3 = 20
Número de ocurrencias de  4 = 20
Número de ocurrencias de  5 = 24
Número de ocurrencias de  6 = 8
El dado está cargado


### Ejercicio 31

Obtenga una distribución de 10 datos según una distribución normal de media 10 y desviación estándar 2. A continuación calcule la media y la desviación estándar de los 10 datos. ¿Se aproximan a los valores con los que fueron generados?

Pruebe a hacer lo mismo pero generando 100, 1.000 y 10.000 datos aleatorios. ¿Se aproxima la media y la desviación estándar más ahora? Escriba el valor absoluto de la diferencia entre los valores promedio de su muestra y 10.

**Nota:** Lo que tratamos de demostrar es que se cumple el *Teorema del límite central* (https://es.wikipedia.org/wiki/Teorema_del_l%C3%ADmite_central)

In [41]:
# Creo el generador de números aleatorios
rng = np.random.default_rng(seed=311343)

for n in [10, 100, 1000, 10000]: # bucle para muestrear con diferentes tamaños
    muestra = rng.normal(10, 2, n) # muestra de una distribución normal
    media = np.mean(muestra)
    desviacion = np.std(muestra)
    print('-' * 40)
    print('Tamaño de la muestra =', n)
    print('(media, std) = (', media, ',', desviacion, ')')
    # la función 'abs' de abajo, está definida de forma nativa en Python. Devuelve el valor absoluto de un número
    print(f'Diferencias en (media, std) = ({abs(10 - media)}, {abs(2 - desviacion)}')

----------------------------------------
Tamaño de la muestra = 10
(media, std) = ( 8.522047836115977 , 1.993098159684404 )
Diferencias en (media, std) = (1.477952163884023, 0.006901840315596042
----------------------------------------
Tamaño de la muestra = 100
(media, std) = ( 9.845542677594318 , 2.3908385946426844 )
Diferencias en (media, std) = (0.15445732240568155, 0.39083859464268444
----------------------------------------
Tamaño de la muestra = 1000
(media, std) = ( 9.980970265510118 , 1.9962117062552844 )
Diferencias en (media, std) = (0.01902973448988199, 0.003788293744715565
----------------------------------------
Tamaño de la muestra = 10000
(media, std) = ( 10.01630885749154 , 1.9921855791521332 )
Diferencias en (media, std) = (0.01630885749153954, 0.007814420847866765
