# Curso de Python Científico
## Ejercicios del módulo de NumPy

---

**Autor:** César Husillos Rodríguez

**Email:** c.husillos@igme.es

---

### Ejercicio1

Genere un array de dimensión 3x3, que tenga
* en la primera fila: 4, 5, 6
* en la segunda fila: 7, 8, 9
* en la tercera fila: 10, 11, 12

Imprima por pantalla el tamaño del array en bytes.

In [6]:
import numpy as np

datos = np.array([[4,5,6], [7,8,9], [10,11,12]])
print(datos)

print(datos.nbytes)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
36


### Ejercicio 2

Cree un array con 10 elementos en el intervalo [-2,2] y equidistantes entre ellos.

In [7]:
datos = np.linspace(-2, 2, 10, endpoint=True)
print(datos)

[-2.         -1.55555556 -1.11111111 -0.66666667 -0.22222222  0.22222222
  0.66666667  1.11111111  1.55555556  2.        ]


### Ejercicio 3

Cree un array cuyos elementos sean los enteros pares en [1,100] y en orden decreciente.

In [8]:
datos = np.arange(100, 0, -2)
print(datos)

[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52  50  48  46  44  42  40  38  36  34  32  30
  28  26  24  22  20  18  16  14  12  10   8   6   4   2]


In [9]:
# help(np.arange)

### Ejercicio 4

Genere un array bidimensional de números enteros aletatorios que tenga 4 filas y 5 columnas. Los aleatorios generados estarán en el intervalo cerrado [0, 10].

In [10]:
datos4 = np.random.randint(0, 11, (4,5))
print(datos4)

[[5 2 6 0 2]
 [8 6 3 8 8]
 [5 9 2 8 9]
 [7 1 6 4 3]]


In [11]:
# help(np.random.randint)

### Ejercicio 5

Genere un array de booleanos a partir del array del ejercicio 4. 

**Nota:** Se trata de hacer un cambio de tipo de dato almacenado por el array.

In [12]:
datos5 = np.full_like(datos4, -2, dtype=bool)
print(datos5)

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [13]:
#help(np.full_like)

### Ejercicio 6

Genere un array a usando las palabras contenidas en la siguiente frase: "En un lugar de La Mancha, de cuyo nombre no quiero acordarme". Imprima el tipo del array por pantalla y las dimensiones de ese array.

**Pista:** Asigne la cadena de caracteres a una variable llamada, por ejemplo, "texto". Después debe "romper" la cadena por los espacios en blanco " " y usar las palabras para crear un array. Esto se puede hacer con el método *split* de Python. Si no se acuerda, use la función help(texto.split) para obtener información.

In [14]:
texto = "En un lugar de La Mancha, de cuyo nombre no quiero acordarme"

In [15]:
#help(texto.split)

In [16]:
palabras = texto.split()
print(palabras)

['En', 'un', 'lugar', 'de', 'La', 'Mancha,', 'de', 'cuyo', 'nombre', 'no', 'quiero', 'acordarme']


In [18]:
datos6 = np.array(palabras)
print('array de palabras = ', datos6)
print('Tamaño del array de palabras =', datos6.size)
print('Forma del array de palabras =', datos6.shape)
print('Tipo del array de palabras =', datos6.dtype)

array de palabras =  ['En' 'un' 'lugar' 'de' 'La' 'Mancha,' 'de' 'cuyo' 'nombre' 'no' 'quiero'
 'acordarme']
Tamaño del array de palabras = 12
Forma del array de palabras = (12,)
Tipo del array de palabras = <U9


### Ejercicio 7

Genere un array de números decimales y de dimensiones 3x1. Todos los elementos del array deben ser igual a 5.0. Imprima su forma (*shape*)

Modifique la forma del array de forma que el resultado sea un array unidimensional. Imprima la nueva forma del array.

In [21]:
datos7 = np.full((3, 1), 5.0)
print(datos7)
print('Forma del array datos7 =', datos7.shape)

# Cambio la forma de datos7 para que sea un array 1D
datos7 = datos7.flatten()
print('Forma del array modificado =', datos7.shape)

[[5.]
 [5.]
 [5.]]
Forma del array datos7 = (3, 1)
Forma del array modificado = (3,)


### Ejercicio 8

Genere un array aleatorio de números enteros entre -5 y 5, que tenga 3 filas y 2 columnas. Imprima el array por pantalla.

Modifique el array de forma que los valores que están en las filas pasen estar en las columnas y viceversa.

**Pista:** Básicamente se le pide que trasponga ese array.

In [23]:
# help(np.random.randint)

In [24]:
datos8 = np.random.randint(-5, 6, size=(3, 2))
print('Array de número enteros aleatorios =')
print(datos8)

# modifico el array para que las filas pasen a columnas y vicecersa. Es lo mismo que "trasponer" un array
datos8 = np.transpose(datos8)
print('Array modificado =')
print(datos8)

Array de número enteros aleatorios =
[[-1 -4]
 [ 3 -3]
 [ 0 -3]]
Array modificado =
[[-1  3  0]
 [-4 -3 -3]]


### Ejercicio 9

Genere un array números enteros crecientes. Contendrá los valores del 0 al 10. Se le pide que:
* muestre el segundo elemento. 
* muestre los dos últimos.
* muestre los elementos que ocupan las posiciones 0, 2, 4, 6, 8 y 10.

In [52]:
datos = np.arange(0,11)
print(datos)

print('Segundo elemento = ', datos[1])
print('Dos últimos elementos = ', datos[-2:]) 
print('Posiciones [0, 2, 4, 6, 8 y 10] = ', datos[::2])

[ 0  1  2  3  4  5  6  7  8  9 10]
Segundo elemento =  1
Dos últimos elementos =  [ 9 10]
Posiciones [0, 2, 4, 6, 8 y 10] =  [ 0  2  4  6  8 10]


### Ejercicio 10

Dado el array que se le muestra en la siguiente celda, seleccione los elementos de las esquinas.

In [55]:
import numpy as np
datos = np.array([[2, 4, 6, 8],[1, 3, -2, 5], [7, 3, 4, 4], [3, 6, 3, 9]])
print(datos)


# Siga escribiendo la solución al ejercicio en la línea siguiente
seleccion_esquinas = datos[[0,0,-1,-1], [0,-1,0,-1]]
print(seleccion_esquinas)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  4 15 19]


### Ejercicio 11

Dado el array definido en la siguiente celda, seleccione los índices adecuados para obtener la submatriz

\begin{matrix}
4 & 6\\
3 & -2\\
3 & 4
\end{matrix}

In [25]:
datos = np.array([[2, 4, 6, 8],[1, 3, -2, 5], [7, 3, 4, 4], [3, 6, 3, 9]])
print(datos)

# Escriba la solución al ejercicio en la siguiente línea de esta celda
solucion = datos[:-1,1:3]
print('solucion =')
print(solucion)

[[ 2  4  6  8]
 [ 1  3 -2  5]
 [ 7  3  4  4]
 [ 3  6  3  9]]
solucion =
[[ 4  6]
 [ 3 -2]
 [ 3  4]]


### Ejercicio 12

Dado el array que se define en la siguiente celda, seleccione e imprima la primera y la tercera fila.

In [28]:
datos = np.arange(20).reshape((10, 2))
print(datos)

# Escriba la solución del ejercicio en la siguiente línea de esta celda
datos12 = datos[[0,2],:]
print('Primera y tercera filas: ')
print(datos12)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
Primera y tercera filas: 
[[0 1]
 [4 5]]


### Ejercicio 13

Dado el tensor (array 3D) definido en la celda siguiente, devuelva la segunda capa mediante indexación.

In [31]:
datos = np.random.randint(low=0, high=10, size=(3, 2, 4))
print(datos)

# Resuelva el ejercicio en las siguientes líneas de esta celda
segunda_capa = datos[1,:,:]
print('Segunda capa:')
print(segunda_capa)

[[[6 7 4 4]
  [8 4 4 4]]

 [[4 4 6 7]
  [5 9 1 4]]

 [[5 1 5 3]
  [4 9 8 5]]]
Segunda capa:
[[4 4 6 7]
 [5 9 1 4]]


### Ejercicio 14

Genere un array con los enteros consecutivos de 20 al 1. Sustituya los números en el intervalo [5, 12] por el valor 0.

In [37]:
# genero el array de enteros consecutivos del 1 al 20
datos14 = np.arange(1, 21)
print(datos14)

# uso un rango que tome los valores del 5 al 12
datos14[4:12] = 0
# invierto el orden del array
datos14 = datos14[::-1]
print('Array modificado:')
print(datos14)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Array modificado:
[20 19 18 17 16 15 14 13  0  0  0  0  0  0  0  0  4  3  2  1]


### Ejercicio 15

Dada la matriz definida en la celda siguiente, sustituya los elementos de la diagonal principal por 1.

In [43]:
datos15 = np.full((5, 5), 2, dtype=int)
print('Array original:')
print(datos15)

# Resuelva el ejercicio en las siguientes líneas de esta celda

# Si lo hacemos seleccionando índices de forma manual, necesitamos 
# cinco índices para filas y cinco para columnas.
ind_fil = np.arange(5, dtype=int) # secuencia de enteros de 0 hasta 4
print('Indices de filas =', ind_fil)

# Ambos índices de la diagonal principal son iguales
ind_col = ind_fil

# Ahora hago el cambio de valor de la diagonal principal
datos15[ind_fil, ind_col] = 1
print('Array modificado: ')
print(datos15)

# La forma elegante y profesional (hay que conocer mucho sobre NumPy porque siempre se escapa algo)
# ind = np.diag_indices_from(datos15)
# datos15[ind] = 1

Array original:
[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]
Indices de filas = [0 1 2 3 4]
Array modificado: 
[[1 2 2 2 2]
 [2 1 2 2 2]
 [2 2 1 2 2]
 [2 2 2 1 2]
 [2 2 2 2 1]]


### Ejercicio 16

Dado el array definido en la siguiente celda, genere otro array en el que los elementos correspondan a la suma de los valores de cada fila del original.

In [ ]:
datos = np.arange(20).reshape((10, 2))
print(datos)

# Escriba la solución del ejercicio en la siguiente línea de esta celda


### Ejercicio 17

Escriba el resultado de calcular la función $\sin(x)$ para aquellos puntos separados $\pi /4$ en el intervalo $[-3\pi, 5\pi]$.

### Ejercicio 18

Dado el conjunto de puntos definidos en el array de la celda siguiente, determine el valor de aplicar el logaritmo en base $e$ al resultado del cálculo de la exponencial de cada elemento.

**Pista:** El problema pide que realice la siguiente operación sobre cada elemento del array: $log_e(e^x)$, donde $x$ es cada uno de los elementos del array.

In [ ]:
datos = np.array([2, 4, 3, 8 ,12])

# Continúe el ejercicio en las líneas siguientes.



### Ejercicio 19

Dados los arrays *a* y *b* definidos en la celda siguiente, determine
* Cuáles son los valores de *a* que están en *b*.
* El número de valores diferentes que hay en *a*.
* Los valores de *a* y de *b* que no están en ambos conjuntos. 

In [ ]:
a = np.array([[2, 3, 6], [5, 5, 7]])
b = np.arange(5)

# Escriba la solución del ejercicio en la siguiente línea de esta celda


### Ejercicio 20

Dado un array de enteros entre 0 y 13, determine aquellos que son impares y múltiplos de 3. Muestrelos por pantalla.

### Ejercicio 21

Dado el array definido en la siguiente celda, devuelva aquellos que corresponden a un año bisiesto. Genere un array con los años bisiestos ordenados de mayor a menor. Escriba también el porcentaje de años bisiestos contenidos en el array.

**Pista:** Un año se considera bisiesto si es múltiplo de 4 y de 100, pero no de 400.

In [ ]:
datos = np.array([4, 1000, 2024, 400, 800, 666, 2012, 2040])

# Escriba la solución del ejercicio en la siguiente línea de esta celda

### Ejercicio 22

Genere un array ordenado de menor a mayor de 20 números enteros aleatorios entre 0 y 13. 

### Ejercicio 23

Obtenga las posiciones del array definido en la siguiente celda de forma que sus valores se ordenen de menor a mayor. Use dichas posiciones para ordenar el array de menor a mayor.

In [ ]:
datos = np.array((0, 1, 15, 8, 9, 17))
print(datos)

# Escriba la solución del ejercicio en la siguiente línea de esta celda

### Ejercicio 24

Dado el array definido en la siguiente celda, elimine los números que sean *np.nan*. Muestre el resultado del array modificado y el número de elementos que contiene.

In [ ]:
datos = np.arange(10, dtype=float)
datos[np.random.randint(0, 10, 3)] = np.nan

print(datos)

# Escriba la solución del ejercicio en la siguiente línea de esta celda

### Ejercicio 25

Genere un array de enteros aleatorios entre 1931 y 2024 y dimensiones 4 x 5. Almacene dicho array en un fichero de nombre 'numeros.csv'. Si abre el fichero con cualquier editor de texto, los números deben estar separados por comas.

### Ejercicio 26

Recupere en un array el contenido del fichero 'numeros.csv'. El array debe ser de números enteros y también debe tener dimensiones 4x5.

### Ejercicio 27

Concatene a las filas del array *a*, las filas del array *b* definidos en la siguiente celda. Muestre el resultado por pantalla.

In [ ]:
a = np.arange(6).reshape((2,3))
b = np.zeros((2, 2), dtype=float)
print('a')
print(a)
print('b')
print(b)

# Escriba la solución del ejercicio en la siguiente línea de esta celda


### Ejercicio 28

Agregue al array *b* del ejercicio anterior una columna más a la izquierda con valores iguales a 1. Concatene las filas del array *a* del ejercicio anterior con el array *b* que acaba de modificar. Muestre el resultado por pantalla. 

### Ejercicio 29

Dado el array de precipitaciones de los ultimos 10 días disponible en la siguiente celda, calcule:
* el acumulado de precipitación diaria.
* La posición del día con menor precipitación.
* El valor de la precipitación máxima.
* el valor mediano, la media y la desviación estándar del conjunto de valores.

In [ ]:
datos = np.array([12.5, 6.1, 0.0, 23.8, 10.4, 5.9, 3.3, 0.0, 0.0])
print(datos)

# Escriba la solución del ejercicio en la siguiente línea de esta celda


### Ejercicio 30

Simule el lanzamiento de un dado 100 veces. Responda a esta pregunta: ¿su dado está cargado?

**Pista:** En un dado equilibrado, existe la misma probabilidad de obtener un número que cualquier otro. Idealmente, las veces que obtenemos un número debería ser igual a $1/6$. A efectos prácticos, consideraremos que un dado está cargado si la probabilidad de obtener un número difiere en un 10% de la probabilidad ideal.

### Ejercicio 31

Obtenga una distibución de 10 datos según una distribución normal de media 10 y desviación estándar 2. A continuación calcule la media y la desviación estándar de los 10 datos. ¿Se aproximan a los valores con los que fueron generados?

Pruebe a hacer lo mismo pero generando 100, 1.000 y 10.000 datos aleatorios. ¿Se aproxima la media y la desviación estándar más ahora? Escriba el valor absoluto de la diferencia entre los valores promedio de su muestra y 10.

**Nota:** Lo que tratamos de demostrar es que se cumple el *Teorema del límite central* (https://es.wikipedia.org/wiki/Teorema_del_l%C3%ADmite_central)